package de.abas.cons.abastl;


public enum AbasIcons {
    ABORT("icon:abort"),
    ABOUT("icon:about"),
    ABOUT_DISABLED("icon:about_disabled"),
    ALARMCLOCK("icon:alarmclock"),
    ARROW_BLUE_DOWN("icon:arrow_blue_down"),
    ARROW_BLUE_DOWN_PLUS("icon:arrow_blue_down_plus"),
    ANOW_BLUE_LEFT("icon:anow_blue_left"),
    ARROW_BLUE_RIGHT("icon:arrow_blue_right"),
    ARROW_BLUE_UP("icon:arrow_blue_up"),
    AT("icon:at"),
    ATTENTION("icon:attention"),
    BALL_BLUE("icon:ball_blue"),
    BALL_GREEN("icon:ball_green"),
    BALL_GREY("icon:ball_grey"),
    BALL_ORANGE("icon:ball_orange"),
    BALL_RED("icon:ball_red"),
    BALL_YELLOW("icon:ball_yellow"),
    BOOK_YELLOW("icon:book_yellow"),
    BOOK_YELLOW_OPEN("icon:book_yellow_open"),
    BOX("icon:box"),
    BOX_DELETE("icon:box_delete"),
    BOX_GREEN("icon:box_green"),
    BOX_RED("icon:box_red"),
    BOX_WHITE("icon:box_white"),
    BULB_OFF("icon:bulb_off"),
    BULB_ON("icon:bulb_on"),
    CLOCK("icon:clock"),
    CONSOLE("icon:console"),
    CUBE_BLUE("icon:cube_blue"),
    CUBE_BLUE_DELETE("icon:cube_blue_delete"),
    CUBE_GREEN("icon:cube_green"),
    CUBE_GREEN_DELETE("icon:cube_green_delete"),
    CUBE_YELLOW("icon:cube_yellow"),
    CUBE_YELLOW_DELETE("icon:cube_yellow_delete"),
    CUBES_BLUE("icon:cubes_blue"),
    CUBES_GREEN("icon:cubes_green"),
    CUBES_YELLOW("icon:cubes_yellow"),
    DATE("icon:date"),
    DATE_DISABLED("icon:date_disabled"),
    DEADEND("icon:deadend"),
    DOCUMENT("icon:document"),
    FIND("icon:find"),
    FLAG_BLUE("icon:flag_blue"),
    FLAG_GREEN("icon:flag_green"),
    FLAG_RED("icon:flag_red"),
    FLAG_YELLOW("icon:flag_yellow"),
    FLASH("icon:flash"),
    FOLDER_CLOSED("icon:folder_closed"),
    FOLDER_OPENED("icon:folder_opened"),
    FOLDER_OPENED_DISABLED("icon:folder_opened_disabled"),
    GARBAGE("icon:garbage"),
    HIERACHY("icon:hierarchy"),
    HOURGLASS("icon:hourglass"),
    HOUSE("icon:house"),
    ICECUBE("icon:icecube"),
    INFORMATION("icon:information"),
    INFOSYSTEM("icon:infosystem"),
    INTERNET("icon:internet"),
    INVISIBLE("icon:invisible"),
    LOCK("icon:lock"),
    LOCK_OPEN("icon:lock_open"),
    MAIL("icon:mail"),
    MEANS_OF_PRODUCTION("icon:means_of_production"),
    MEDIA_PAUSE_GREEN("icon:media_pause_green"),
    MEDIA_PLAY_BLUE("icon:media_play_blue"),
    MEDIA_PLAY_GREEN("icon:media_play_green"),
    MEDIA_STOP_GREEN("icon:media_stop_green"),
    MESSAGE("icon:message"),
    MESSAGE_DISABLED("icon:message_disabled"),
    MINUS("icon:minus"),
    MINUS_BLACK("icon:minus_black"),
    MOBILE("icon:mobile"),
    OK("icon:ok"),
    OPERATION("icon:operation"),
    PACKAGE("icon:package"),
    PACKAGE_DELETE("icon:package_delete"),
    PACKAGE_ERROR("icon:package_error"),
    PLIERS_ARROW_OUT("icon:pliers_arrow_out"),
    PLUS("icon:plus"),
    PLUS_BLACK("icon:plus_black"),
    PREFERENCES("icon:preferences"),
    PREFERENCES_DISABLED("icon:preferences_disabled"),
    PRINT("icon:print"),
    PROCESS("icon:process"),
    PRODUCT("icon:product"),
    PRODUCTS("icon:products"),
    RECYCLE("icon:recycle"),
    REPLACE("icon:replace"),
    REPLACE_DISABLED("icon:replace_disabled"),
    SAVE("icon:save"),
    SCREEN_ADD("icon:screen_add"),
    SCREEN_ADD_DISABLED("icon:screen_add_disabled"),
    SCREEN_COPY("icon:screen_copy"),
    SCREEN_DELETE("icon:screen_delete"),
    SCREEN_EDIT("icon:screen_edit"),
    SCREEN_EMPTY("icon:screen_empty"),
    SCREEN_EXTRAS("icon:screen_extras"),
    SCREEN_NEW("icon:screen_new"),
    SCREEN_SELECTION("icon:screen_selection"),
    SCREEN_SELECTION_DISABLED("icon:screen_selection_disabled"),
    SCREEN_VIEW("icon:screen_view"),
    SCREWDRIVER("icon:SCREWDRIVER"),
    SEARCH("icon:search"),
    SEARCH_DISABLED("icon:search_disabled"),
    SELECTION("icon:selection"),
    SHOPPINGCART("icon:shoppingcart"),
    SHOPPINGCART_ARROW_INTO("icon:shoppingcart_arrow_into"),
    STAR_RED("icon:star_red"),
    STOP("icon:stop"),
    STOP2("icon:stop2"),
    TELEPHONE("icon:telephone"),
    TEXT("icon:text"),
    TEXT2("icon:text2"),
    TEXT_DELETE("icon:text_delete"),
    TEXT_EDIT("icon:text_edit"),
    TEXT_EDIT_DISABLED("icon:text_edit_disabled"),
    TEXT_EMPTY("icon:text_empty"),
    TEXT_EMPTY_DISABLED("icon:text_empty_disabled"),
    TEXT_NEW("icon:text_new"),
    TEXT_NEW_DISABLED("icon:text_new_disabled"),
    TRANSFER_MINUS("icon:transfer_minus"),
    TRANSFER_PLUS("icon:transfer_plus"),
    USER("icon:user"),
    VIEW("icon:view"),
    VIEW_DISABLED("icon:view_disabled"),
    VISIBLE("icon:visible"),
    WORKSTATION("icon:workstation");

    private final String value;

    AbasIcons(final String value) {
        this.value = value;
    }

    /**
     * gets the string for the specific icon
     *
     * @return - a string for the icon
     */
    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return value;
    }
}